//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoVenda
    {
        public int fid { get; set; }
        public int codigo_produto { get; set; }
        public Nullable<double> valor_ano_corrente { get; set; }
        public Nullable<double> valor_3_anos { get; set; }
    
        public virtual Franqueado Franqueado { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
