//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosProduto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidosProduto()
        {
            this.RespostaPedidoes = new HashSet<RespostaPedido>();
        }
    
        public int ppid { get; set; }
        public Nullable<int> codigo_produto { get; set; }
        public Nullable<int> quantidade { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual Produto Produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespostaPedido> RespostaPedidoes { get; set; }
    }
}
