//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespostaPedido
    {
        public int rid { get; set; }
        public int ppid { get; set; }
        public Nullable<double> preco { get; set; }
        public Nullable<int> quantidade { get; set; }
        public Nullable<bool> resposta { get; set; }
    
        public virtual PedidosProduto PedidosProduto { get; set; }
    }
}
