//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public int vid { get; set; }
        public int fid { get; set; }
        public int cid { get; set; }
        public int tid { get; set; }
        public Nullable<int> codigo_produto { get; set; }
        public Nullable<System.DateTime> data_venda { get; set; }
        public Nullable<double> preco_venda { get; set; }
        public Nullable<int> quantidade { get; set; }
    
        public virtual Franqueado Franqueado { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
